# Generated by Django 4.1.7 on 2024-05-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surnatural_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaires',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('commentaire', models.TextField(max_length=400)),
            ],
            options={
                'db_table': 'Commentaires',
            },
        ),
    ]
