# Generated by Django 4.1.7 on 2024-05-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surnatural_app', '0002_commentaires'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='img',
            field=models.ImageField(null=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='services',
            name='logo',
            field=models.ImageField(null=True, upload_to='img'),
        ),
    ]
