# Generated by Django 4.1.7 on 2024-05-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surnatural_app', '0003_services_img_services_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=50)),
            ],
            options={
                'db_table': 'Publicites',
            },
        ),
    ]
