# Generated by Django 4.1.7 on 2024-05-14 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surnatural_app', '0005_alter_publicites_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicites',
            name='description',
            field=models.TextField(max_length=300),
        ),
    ]
