# Generated by Django 4.1.7 on 2024-05-20 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('surnatural_app', '0007_publications_reactions_publications_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reactions',
            name='like',
        ),
        migrations.AddField(
            model_name='reactions',
            name='commentaire',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterModelTable(
            name='reactions',
            table='Reaction',
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False)),
                ('date_like', models.DateField(auto_now=True)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surnatural_app.publications')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Likes',
            },
        ),
    ]
