# Generated by Django 4.1.7 on 2024-05-20 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surnatural_app', '0008_remove_reactions_like_reactions_commentaire_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='publications',
            table='Publications',
        ),
    ]
