# Generated by Django 4.1.7 on 2024-07-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surnatural_app', '0009_alter_publications_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaires',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
